"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["quick-gray.py"]
APP_NAME = "QuickGrayscale"

DATA_FILES = ["status-bar-logo.png"]
OPTIONS = {
    "iconfile":"./assets/gq.icns",
    "plist": {
        "CFBundleName": "QuickGrayscale",
        "CFBundleDisplayName": "Quick Grayscale",
        "CFBundleIdentifier": "com.shubham.quickgrayscale",
        "CFBundleVersion": "0.1.0",
        "CFBundleShortVersionString": "0.1.0",
        "LSUIElement": True # Launch on startup
    },
    "packages": ["rumps"]
}

setup(
    name="Quick Grayscale",
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"]
)