"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["quick-gray.py"]
DATA_FILES = ["./assets/"]
OPTIONS = {
    "iconfile":"./assets/qg.icns",
    "plist": {
        "LSUIElement": True,
    },
    "packages": ["rumps"]
}

setup(
    name="Quick Grayscale",
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"]
)